version: '3'

services:
  web:
    build: ./Project/.
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
      
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./.env
