version: '3'

services:
  postgres_db:
    image: postgres:14-alpine
    env_file:
      - ./.env
  web:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py seeds &&
             python manage.py runserver 0.0.0.0:8000" 
             
      
